"""Leakage-safe Random Forest Robust (RFR) gap filling for eddy-covariance data.

Reproduces the method of Zhu et al. (2022), *Stable gap-filling for longer eddy
covariance data gaps*, Agricultural and Forest Meteorology 314, 108777,
https://doi.org/10.1016/j.agrformet.2021.108777

The frozen scientific specification this package is checked against lives in
``docs/method_spec.md`` (prose) and ``docs/method_spec.yaml`` (machine readable).
Numerical reproduction targets and their supplementary sources are recorded in
``docs/supplement_benchmarks.md``.

The public API is assembled incrementally as the implementation steps land; see
``docs/method_spec.md`` for the contract each module must satisfy.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _version

from rfrgapfill.benchmarks import (
    BENCHMARK_TABLE_COLUMNS,
    COMPARISON_TABLE_COLUMNS,
    NEE_BENCHMARK_UNITS,
    NEE_MODEL_UNITS,
    NEE_RATE_TO_G_C_PER_DAY,
    PUBLISHED_BENCHMARKS,
    BenchmarkError,
    PublishedBenchmark,
    benchmark_table,
    compare_to_benchmarks,
    convert_nee_to_carbon_units,
)
from rfrgapfill.config import (
    DEFAULT_HYPERPARAMETER_GRID,
    HYPERPARAMETER_PRESETS,
    AllocationBasis,
    BoundaryConvention,
    ColumnMap,
    ColumnMapError,
    ConfigError,
    CVStrategy,
    DailyStatisticStrategy,
    FeatureConfig,
    FeatureMode,
    GapClass,
    GapScenarioConfig,
    Hemisphere,
    HyperparameterPreset,
    MetricSubset,
    Mode,
    R2Definition,
    RFRConfig,
    ValidationConfig,
    load_config,
    orf_pairing_differences,
    require_orf_pairing,
)
from rfrgapfill.features import (
    RADIATION_CATEGORY,
    SEASON,
    FeatureError,
    RadiationClass,
    Season,
    build_feature_matrix,
    daily_flux_statistics,
    feature_names,
    radiation_tag,
    receptive_limiter_features,
    season_tag,
    time_distance_hours,
)
from rfrgapfill.fill import (
    FILL_COLUMN_SUFFIXES,
    FillError,
    FillMethod,
    FillReport,
    FillResult,
    RFRGapFiller,
    fill_column_names,
    method_label,
)
from rfrgapfill.gaps import (
    GAP_MANIFEST_COLUMNS,
    ArtificialGap,
    GapAllocation,
    GapError,
    GapManifest,
    GapScenarioGenerator,
    GapScenarioWarning,
    allocate_gaps,
)
from rfrgapfill.leakage import (
    LeakageError,
    ValidationFeatureSet,
    available_target_mask,
    build_validation_features,
    detect_target_leakage,
    hide_target,
    holdout_mask_from_intervals,
    observed_target_mask,
    require_no_target_leakage,
)
from rfrgapfill.legacy import (
    LegacyFluxlibWarning,
    build_legacy_features,
    legacy_feature_names,
)
from rfrgapfill.metrics import (
    CoreMetrics,
    EnergyBalanceComparison,
    MetricError,
    bias,
    compare_energy_balance,
    core_metrics,
    energy_balance_ratio,
    r2,
    regression_slope,
    rmse,
)
from rfrgapfill.model import (
    FitReport,
    IncompletePolicy,
    InsufficientTrainingDataError,
    ModelError,
    NotFittedError,
    RFRModel,
)
from rfrgapfill.plotting import (
    PlottingError,
    plot_benchmark_comparison,
    plot_gap_length_grid,
    plot_gap_length_sensitivity,
)
from rfrgapfill.provenance import (
    MANIFEST_FORMAT,
    MANIFEST_VERSION,
    REQUIRED_FIELDS,
    ProvenanceError,
    RowCounts,
    RunKind,
    RunManifest,
    ambiguity_choices,
    environment_versions,
    load_manifest,
)
from rfrgapfill.sensitivity import (
    DEFAULT_TARGET_UNITS,
    GAP_CLASS_ORDER,
    METHOD_ORDER,
    SENSITIVITY_TABLE_COLUMNS,
    SITE_MEDIAN_TABLE_COLUMNS,
    SUBSET_ORDER,
    SensitivityError,
    gap_length_pivot,
    gap_length_table,
    median_across_sites,
)
from rfrgapfill.sites import (
    IGBP_CLASSES,
    METHOD_DIFFERENCE_COLUMNS,
    SITE_METADATA_COLUMNS,
    SITE_REPORT_COLUMNS,
    STRATIFIED_SUMMARY_COLUMNS,
    TABLE_S10_COMPARISONS,
    WELCH_TABLE_COLUMNS,
    PublishedWelchComparison,
    SiteReportError,
    SiteReportWarning,
    compare_to_table_s10,
    method_differences,
    published_welch_table,
    read_table_s2,
    read_table_s9,
    read_tables_s4_to_s6,
    site_level_evidence,
    site_metadata,
    site_population_summary,
    site_report,
    stratified_summary,
    welch_comparison,
)
from rfrgapfill.synthetic import (
    DEFAULT_KNOWN_GAPS,
    KnownGap,
    SyntheticSite,
    known_gap_manifest,
    synthetic_site,
)
from rfrgapfill.features import (
    DailyStatistics,
    FeatureError,
    FeatureMatrix,
    build_feature_matrix,
    daily_flux_statistics,
    feature_names,
    radiation_tag,
    season_tag,
    time_distance_hours,
)
from rfrgapfill.fill import FillResult, RFRGapFiller
from rfrgapfill.fluxnet import (
    FLUXNET2015_FLUX_QC,
    FLUXNET2015_FLUXES,
    FLUXNET2015_MISSING_VALUE,
    FLUXNET2015_QC_FLAGS,
    FluxnetAvailability,
    FluxnetError,
    QCSummary,
    fluxnet_column_map,
    inspect_fluxnet,
    prepare_fluxnet_frame,
    qc_summary,
    read_fluxnet_csv,
)
from rfrgapfill.gaps import (
    ArtificialGaps,
    GapError,
    GapScenarioGenerator,
    generate_artificial_gaps,
)
from rfrgapfill.metrics import (
    CoreMetrics,
    MetricError,
    SubsetMetrics,
    bias,
    core_metrics,
    daytime_mask,
    energy_balance_ratio,
    metrics_by_subset,
    metrics_from_config,
    nighttime_mask,
    r2,
    regression_slope,
    rmse,
)
from rfrgapfill.model import ModelError, RFRModel, TrainingReport, model_version
from rfrgapfill.provenance import environment, observed_mask, run_manifest
from rfrgapfill.time import (
    TIME_DISTANCE_HOURS,
    DuplicatePolicy,
    TimeAxis,
    TimestampError,
    elapsed_hours,
    prepare_time_index,
)
from rfrgapfill.uncertainty import (
    BIAS_IQR_TABLE_COLUMNS,
    TABLE_S8_RANGES,
    UNCERTAINTY_RANGE_TABLE_COLUMNS,
    PublishedUncertaintyRange,
    UncertaintyError,
    bias_iqr,
    published_uncertainty_table,
)
from rfrgapfill.validation import (
    BIAS_SPREAD_TABLE_COLUMNS,
    ENERGY_BALANCE_TABLE_COLUMNS,
    METRIC_TABLE_COLUMNS,
    BiasSpread,
    EnergyBalanceCheck,
    TargetValidation,
    ValidationError,
    ValidationReport,
    ValidationWarning,
    daytime_mask,
    gap_class_labels,
    subset_masks,
    validate_rfr,
)

try:  # pragma: no cover - trivial packaging fallback
    __version__ = _version("rfr-gapfill")
except PackageNotFoundError:  # pragma: no cover - source tree without install
    __version__ = "0.0.0.dev0"

#: Path-independent identifier recorded in run manifests and fill provenance.
PAPER_DOI = "10.1016/j.agrformet.2021.108777"

__all__ = [
    "BENCHMARK_TABLE_COLUMNS",
    "BIAS_IQR_TABLE_COLUMNS",
    "BIAS_SPREAD_TABLE_COLUMNS",
    "COMPARISON_TABLE_COLUMNS",
    "DEFAULT_HYPERPARAMETER_GRID",
    "DEFAULT_KNOWN_GAPS",
    "DEFAULT_TARGET_UNITS",
    "ENERGY_BALANCE_TABLE_COLUMNS",
    "FILL_COLUMN_SUFFIXES",
    "GAP_CLASS_ORDER",
    "GAP_MANIFEST_COLUMNS",
    "HYPERPARAMETER_PRESETS",
    "IGBP_CLASSES",
    "MANIFEST_FORMAT",
    "MANIFEST_VERSION",
    "METHOD_DIFFERENCE_COLUMNS",
    "METHOD_ORDER",
    "METRIC_TABLE_COLUMNS",
    "NEE_BENCHMARK_UNITS",
    "NEE_MODEL_UNITS",
    "NEE_RATE_TO_G_C_PER_DAY",
    "PAPER_DOI",
    "PUBLISHED_BENCHMARKS",
    "RADIATION_CATEGORY",
    "REQUIRED_FIELDS",
    "SEASON",
    "SENSITIVITY_TABLE_COLUMNS",
    "SITE_MEDIAN_TABLE_COLUMNS",
    "SITE_METADATA_COLUMNS",
    "SITE_REPORT_COLUMNS",
    "STRATIFIED_SUMMARY_COLUMNS",
    "SUBSET_ORDER",
    "TABLE_S8_RANGES",
    "TABLE_S10_COMPARISONS",
    "TIME_DISTANCE_HOURS",
    "UNCERTAINTY_RANGE_TABLE_COLUMNS",
    "WELCH_TABLE_COLUMNS",
    "AllocationBasis",
    "ArtificialGap",
    "BenchmarkError",
    "BiasSpread",
    "BoundaryConvention",
    "CVStrategy",
    "ColumnMap",
    "ColumnMapError",
    "ConfigError",
    "CoreMetrics",
    "DailyStatisticStrategy",
    "DuplicatePolicy",
    "EnergyBalanceCheck",
    "EnergyBalanceComparison",
    "FeatureConfig",
    "FeatureError",
    "FeatureMode",
    "FillError",
    "FillMethod",
    "FillReport",
    "FillResult",
    "FitReport",
    "GapAllocation",
    "GapClass",
    "GapError",
    "GapManifest",
    "GapScenarioConfig",
    "GapScenarioGenerator",
    "GapScenarioWarning",
    "Hemisphere",
    "HyperparameterPreset",
    "IncompletePolicy",
    "InsufficientTrainingDataError",
    "KnownGap",
    "LeakageError",
    "LegacyFluxlibWarning",
    "MetricError",
    "MetricSubset",
    "Mode",
    "ModelError",
    "NotFittedError",
    "PlottingError",
    "ProvenanceError",
    "PublishedBenchmark",
    "PublishedUncertaintyRange",
    "PublishedWelchComparison",
    "R2Definition",
    "RFRConfig",
    "RFRGapFiller",
    "RFRModel",
    "RadiationClass",
    "RowCounts",
    "RunKind",
    "RunManifest",
    "Season",
    "SensitivityError",
    "SiteReportError",
    "SiteReportWarning",
    "SyntheticSite",
    "TargetValidation",
    "TimeAxis",
    "TimestampError",
    "UncertaintyError",
    "ValidationConfig",
    "ValidationError",
    "ValidationFeatureSet",
    "ValidationReport",
    "ValidationWarning",
    "__version__",
    "allocate_gaps",
    "ambiguity_choices",
    "available_target_mask",
    "benchmark_table",
    "bias",
    "bias_iqr",
    "build_feature_matrix",
    "build_legacy_features",
    "build_validation_features",
    "compare_energy_balance",
    "compare_to_benchmarks",
    "compare_to_table_s10",
    "convert_nee_to_carbon_units",
    "core_metrics",
    "daily_flux_statistics",
    "daytime_mask",
    "detect_target_leakage",
    "elapsed_hours",
    "energy_balance_ratio",
    "environment_versions",
    "feature_names",
    "fill_column_names",
    "gap_class_labels",
    "gap_length_pivot",
    "gap_length_table",
    "hide_target",
    "holdout_mask_from_intervals",
    "known_gap_manifest",
    "legacy_feature_names",
    "load_config",
    "load_manifest",
    "median_across_sites",
    "method_differences",
    "method_label",
    "observed_target_mask",
    "orf_pairing_differences",
    "plot_benchmark_comparison",
    "plot_gap_length_grid",
    "plot_gap_length_sensitivity",
    "prepare_time_index",
    "published_uncertainty_table",
    "published_welch_table",
    "r2",
    "radiation_tag",
    "read_table_s2",
    "read_table_s9",
    "read_tables_s4_to_s6",
    "receptive_limiter_features",
    "regression_slope",
    "require_no_target_leakage",
    "require_orf_pairing",
    "rmse",
    "season_tag",
    "site_level_evidence",
    "site_metadata",
    "site_population_summary",
    "site_report",
    "stratified_summary",
    "subset_masks",
    "synthetic_site",
    "time_distance_hours",
    "validate_rfr",
    "welch_comparison",
]
